export = LegalForm;
/**
 * Legal form types
 * @type {{UNKNOWN:number, SOLE_PROPRIETORSHIP:number, LIMITED_LIABILITY_COMPANY:number, GENERAL_PARTNERSHIP:number, JOINT_STOCK_COMPANY:number, LIMITED_PARTNERSHIP:number, PRIVATE_LIMITED_LIABILITY_COMPANY:number, SINGLE_MEMBER_JOINT_STOCK_COMPANY:number, SIMPLE_LIMITED_LIABILITY_COMPANY:number, SINGLE_MEMBER_LIMITED_LIABILITY_COMPANY:number,SIMPLIFIED_JOINT_STOCK_COMPANY:number, SMALL_COMPANY:number, LIMITED_JOINT_STOCK_PARTNERSHIP:number, PROFESSIONAL_PARTNERSHIP:number, LIMITED_LIABILITY_PARTNERSHIP:number, PRIVATE_PARTNERSHIP:number, LIMITED_LIABILITY_COMPANY_LIMITED_PARTNERSHIP:number, LIMITED_LIABILITY_COMPANY_LIMITED_JOINT_STOCK_PARTNERSHIP:number, PUBLIC_INSTITUTION:number}}
 */
declare const LegalForm: {
    UNKNOWN: number;
    SOLE_PROPRIETORSHIP: number;
    LIMITED_LIABILITY_COMPANY: number;
    GENERAL_PARTNERSHIP: number;
    JOINT_STOCK_COMPANY: number;
    LIMITED_PARTNERSHIP: number;
    PRIVATE_LIMITED_LIABILITY_COMPANY: number;
    SINGLE_MEMBER_JOINT_STOCK_COMPANY: number;
    SIMPLE_LIMITED_LIABILITY_COMPANY: number;
    SINGLE_MEMBER_LIMITED_LIABILITY_COMPANY: number;
    SIMPLIFIED_JOINT_STOCK_COMPANY: number;
    SMALL_COMPANY: number;
    LIMITED_JOINT_STOCK_PARTNERSHIP: number;
    PROFESSIONAL_PARTNERSHIP: number;
    LIMITED_LIABILITY_PARTNERSHIP: number;
    PRIVATE_PARTNERSHIP: number;
    LIMITED_LIABILITY_COMPANY_LIMITED_PARTNERSHIP: number;
    LIMITED_LIABILITY_COMPANY_LIMITED_JOINT_STOCK_PARTNERSHIP: number;
    PUBLIC_INSTITUTION: number;
};
